# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandR', '0001_initial'),
        ('user', '0002_auto_20180827_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='new',
        ),
        migrations.AddField(
            model_name='thread',
            name='newFor',
            field=models.ManyToManyField(related_name='new_threads', to='LandR.User'),
        ),
    ]
